DROP DATABASE IF EXISTS DNDChars_db;
CREATE DATABASE DNDChars_db;
USE DNDChars_db;
CREATE TABLE users  (id INTEGER(5) AUTO_INCREMENT NOT NULL,
email VARCHAR(45) NOT NULL, PRIMARY KEY(id)
);


CREATE TABLE characters ( id INTEGER(5) AUTO_INCREMENT NOT NULL,
 userEmail VARCHAR(30) NOT NULL, strength INTEGER(5) NOT NULL, dexterity INTEGER(5) NOT NULL, constitution INTEGER(5) NOT NULL, intelligence INTEGER(5) NOT NULL, wisdom INTEGER(5) NOT NULL, charisma INTEGER(5) NOT NULL, armor_class INTEGER(5) NOT NULL, speed INTEGER(5) NOT NULL, hitpoints INTEGER(5) NOT NULL, initiative INTEGER(5) NOT NULL, charName VARCHAR(45) NOT NULL, charClass VARCHAR(45) NOT NULL, charLevel INTEGER(5) NOT NULL, charAlignment VARCHAR(45) NOT NULL, charBackground VARCHAR(150), charPersonality VARCHAR(45), charInventory VARCHAR(200),
  PRIMARY KEY(id));
